openapi: 3.0.0
info:
  title: "PowerFind Endpoints"
  description: "PowerFind API for managing powerbanks and locations"
  version: snapshot

paths:
  /public/location:
    get:
      summary: Get available locations for powerbanks
      operationId: getLocation
      responses:
        200:
          description: Get locations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationResponse'
    post:
      summary: Add new location for powerbank
      operationId: postLocation
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
        - name: district
          in: query
          required: true
          schema:
            type: string
        - name: address
          in: query
          required: true
          schema:
            type: string
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        200:
          description: Create new location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResponse'
        400:
          $ref: "#/components/responses/BadRequest"

  /public/powerbank:
    get:
      summary: Get available powerbank for user
      operationId: getPowerbank
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: powerbankId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: requestedDurationMinutes
          in: query
          required: false
          schema:
            type: integer
          description: Number of minutes the user wants to take the powerbank
      responses:
        200:
          description: Get powerbank
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResponse'
        400:
          $ref: "#/components/responses/BadRequest"
    post:
      summary: Add new powerbank
      operationId: postPowerbank
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPowerbankRequest'
      responses:
        200:
          description: Add new powerbank
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResponse'
        400:
          $ref: "#/components/responses/BadRequest"

components:
  schemas:
    LocationResponse:
      type: array
      items:
        $ref: '#/components/schemas/Location'

    Location:
      type: object
      properties:
        streetAddress:
          type: string
        city:
          type: string
        district:
          type: string

    EditResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    BadRequestResponse:
      required:
        - message
      properties:
        message:
          type: string

    NewPowerbankRequest:
      type: object
      required:
        - model
        - voltage
        - health
        - capacity
        - city
        - district
        - latitude
        - longitude
        - address
      properties:
        model:
          type: string
        voltage:
          type: integer
        health:
          type: string
        capacity:
          type: integer
        pricePerMinute:
          type: number
          format: decimal
        city:
          type: string
        district:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        address:
          type: string
        maintenanceNote:
          type: string

  responses:
    BadRequest:
      description: Bad request (400)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestResponse'
