spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/powerDB
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
