name: CI Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests and build JAR
        run: ./gradlew clean build

      - name: Prepare Kaniko credentials
        run: |
          mkdir -p "${{ runner.temp }}/docker"
          cat <<EOF > "${{ runner.temp }}/docker/config.json"
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "${{ secrets.DOCKER_USERNAME }}",
                "password": "${{ secrets.DOCKER_TOKEN }}"
              }
            }
          }
          EOF

      - name: Build and push Docker image with Kaniko
        run: |
          docker run \
            -v "${{ github.workspace }}:/workspace" \
            -v "${{ runner.temp }}/docker:/kaniko/.docker" \
            gcr.io/kaniko-project/executor:latest \
            --context /workspace \
            --dockerfile /workspace/Dockerfile \
            --destination docker.io/${{ secrets.DOCKER_USERNAME }}/powerfind:${{ github.sha }} \
            --cache=true
