name: CI Build with Compose and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    env:
      SPRING_PROFILES_ACTIVE: local
      SPRING_LIQUIBASE_ENABLED: true
      IMAGE_NAME: harut20024/powerfind
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin
          cache: gradle

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests (Testcontainers PostgreSQL)
        run: ./gradlew clean test

      - name: Build Spring Boot JAR
        run: ./gradlew bootJar

      - name: Start PostgreSQL with Docker Compose
        run: docker compose up -d postgres

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for Postgres..."
          docker run --network host --rm busybox:1.36.1 \
            sh -c 'until nc -z localhost 5432; do sleep 1; done'

      - name: Build app Docker image with Compose
        run: docker compose build

      - name: Tag and Push image manually
        run: |
          docker tag power-postgres docker.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push docker.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}
