name: CI Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: haruttarzyan/powerfind
      TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests and build JAR
        run: ./gradlew clean build

      - name: Create Kaniko Docker config
        run: |
          mkdir -p /kaniko/.docker
          echo '{"auths":{"https://index.docker.io/v1/":{"username":"${{ secrets.DOCKER_USERNAME }}","password":"${{ secrets.DOCKER_TOKEN }}"}}}' > /kaniko/.docker/config.json

      - name: Build and push Docker image with Kaniko
        uses: aevea/action-kaniko@v0.10.0
        with:
          image: gcr.io/kaniko-project/executor:latest
          args: >
            --dockerfile Dockerfile
            --context ${{ github.workspace }}
            --destination docker.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}
